Repository codestates-beb/BEB-06-SHEPHERD, pull requests merged in 2022-11, with the labels that each got.

#4 [Client] Create-React-App으로 React App 생성
  README.md
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.js
  client/src/App.test.js
  client/src/index.js
  client/src/setupTests.js
Labels: 프론트엔드(frontend), 기능 추가(new feature)

#5 [Client] 프로젝트 셋업
  client/src/App.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/Login.js
  client/src/components/Map.js
  client/src/index.js
  client/src/pages/About.js
  client/src/pages/Dashboard.js
  client/src/pages/Main.js
  client/src/pages/Transaction.js
Labels: 개선안(enhancement), 프론트엔드(frontend), 기능 추가(new feature)

#7 [Client] BaseLayout 컴포넌트, MapChart 컴포넌트, Contact 페이지 라우팅
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.test.js
  client/src/assets/topoJson/skorea-municipalities-2018-topo.json
  client/src/components/BaseLayout.js
  client/src/components/Map.js
  client/src/components/MapChart.js
  client/src/index.js
  client/src/pages/Contact.js
  client/src/pages/Error.js
  client/src/pages/Main.js
  client/src/pages/Transaction.js
Labels: 개선안(enhancement), 프론트엔드(frontend), 기능 추가(new feature)

#11 헤더 라우팅 기능 추가
  client/src/components/About.js
  client/src/components/Header.js
  client/src/components/MakeTransfer.js
  client/src/index.js
Labels: 프론트엔드(frontend), 기능 추가(new feature)

#10 [Client] 레이아웃 컴포넌트 변경, 대쉬보드 추가[WIP]
  client/package-lock.json
  client/package.json
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/MakeOrder.js
  client/src/components/MakeTransfer.js
  client/src/components/MapChart.js
  client/src/components/OrderList.js
  client/src/components/TransactionDetail.js
  client/src/components/TransactionList.js
  client/src/components/TransferDetail.js
  client/src/components/base/BaseContainer.js
  client/src/components/base/BaseLayout.js
  client/src/components/base/BaseStack.js
  client/src/features/schema.js
  client/src/index.js
  client/src/pages/Dashboard.js
Labels: 개선안(enhancement), 프론트엔드(frontend), 기능 추가(new feature)

#14 feat: login or logout에 따른 접근 권한 분리
  .DS_Store
  client/src/App.js
  client/src/components/Header.js
  client/src/components/Login.js
  client/src/components/PrivateRoute.js
  client/src/components/isLogin.js
  client/src/index.js
Labels: 개선안(enhancement), 프론트엔드(frontend)

#13 [Client] 트랜젝션 목록 Display
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/TransactionList.js
  client/src/features/parseObject.js
  client/src/features/schema.js
  client/src/index.js
Labels: 개선안(enhancement), 프론트엔드(frontend), 기능 추가(new feature)

#16 feat: Footer에 팀원 Github 링크 추가 및 로그인 관련 컴포넌트 추가
  client/src/components/Auth.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/Login.js
  client/src/components/isLogin.js
Labels: 프론트엔드(frontend), 기능 추가(new feature)

#17 makeOrder 컴포넌트 추가
  .gitignore
  client/src/App.js
  client/src/components/MakeOrder.js
  client/src/components/TransactionList.js
  client/src/features/schema.js
  client/src/pages/Dashboard.js
  client/src/pages/Error.js
Labels: 프론트엔드(frontend), 기능 추가(new feature)

#18 루트 폴더 gitignore
  .gitignore
Labels: 백엔드(backend)

#26 클라이언트 병합
  .gitignore
  README.md
  client/.gitignore
  client/README.md
  client/jsconfig.json
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.js
  client/src/README.md
  client/src/assets/topoJson/skorea-municipalities-2018-topo.json
  client/src/components/Auth.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/MakeOrder.js
  client/src/components/MapChart.js
  client/src/components/OrderList.js
  client/src/components/PrivateRoute.js
  client/src/components/TransactionList.js
  client/src/components/base/BaseLayout.js
  client/src/components/base/BaseStack.js
  client/src/features/parseObject.js
  client/src/features/schema.js
  client/src/index.js
  client/src/pages/Dashboard.js
  client/src/pages/Error.js
  client/src/pages/Main.js
  client/src/setupTests.js
Labels: 프론트엔드(frontend)

#28 클라이언트 병합 관련
  client/src/components/Auth.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/Login.js
  client/src/index.js
Labels: 프론트엔드(frontend)

#33 충돌 해소용 PR
  .gitignore
Labels: 프론트엔드(frontend)

#38 도커 파일 브랜치 생성
  .gitignore
  docker/network/.gitignore
  docker/network/configs/networkConfig.json
  docker/network/docker-compose.yml
  docker/node/.gitignore
  docker/node/Dockerfile
  docker/node/configs/config.toml
Labels: 백엔드(backend)

#39 [Docker] Node Configs
  .gitignore
  docker/network/.gitignore
  docker/network/docker-compose.yml
  docker/node/.gitignore
  docker/node/Dockerfile
  docker/node/configs/config.toml
  docker/node/configs/networkConfig.json
  docker/node/docker-compose.yml
Labels: 백엔드(backend)

#40 [Docker] Readme 추가
  README.md
  docker/node/Dockerfile
  docker/node/README.md
  docker/node/configs/node.toml
  docker/node/docker-compose.yml
Labels: 백엔드(backend)

#41 [도커] 테스트
  .gitignore
  docker/node/Dockerfile
  docker/node/configs/networkConfig.json
  docker/node/configs/node.toml
  docker/node/docker-compose.yml
Labels: 백엔드(backend)

#45 충돌 해결 이후 서버 병합
  .gitignore
  server/.DS_Store
  server/app.js
  server/controllers/contact.controllers.js
  server/controllers/tx.controllers.js
  server/controllers/user.controllers.js
  server/models/http-error.js
  server/models/user.models.js
  server/package.json
  server/routes/contact.route.js
  server/routes/tx.route.js
  server/truffle/contracts/.gitkeep
  server/truffle/contracts/erc1155contract.sol
  server/truffle/migrations/.gitkeep
  server/truffle/test/.gitkeep
  server/truffle/truffle-config.js
Labels: 백엔드(backend), 기능 추가(new feature)

#49 [Docker] 네트워크 세팅
  .gitignore
  docker/README.md
  docker/configs/networkConfig.json
  docker/configs/node.toml
  docker/docker-compose.yml
  docker/node/Dockerfile
  docker/node/docker-compose.yml
Labels: 백엔드(backend)

#53 [클라이언트] Responsive Design
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/base/BaseLayout.js
  client/src/index.js
Labels: 개선안(enhancement), 프론트엔드(frontend)

#54 [Docker] 개인 노드 템플릿
  docker/README.md
  docker/configs/networkConfig.json
  docker/configs/node.toml
  docker/data/README.md
  docker/docker-compose.yml
Labels: 백엔드(backend)

#56 [Docker] Minor Fix
  docker/configs/node.toml
Labels: 백엔드(backend)

#57 [백엔드] Dev 병합
  contract/abi/shepherdabi.js
  contract/build/contracts/Address.json
  contract/build/contracts/Context.json
  contract/build/contracts/ERC1155.json
  contract/build/contracts/ERC165.json
  contract/build/contracts/IERC1155.json
  contract/build/contracts/IERC1155MetadataURI.json
  contract/build/contracts/IERC1155Receiver.json
  contract/build/contracts/IERC165.json
  contract/build/contracts/Ownable.json
  contract/build/contracts/Shepherd.json
  contract/contracts/.gitkeep
  contract/contracts/Shepherd.sol
  contract/migrations/.gitkeep
  contract/migrations/1_deploy_contracts.js
  contract/package.json
  contract/test/.gitkeep
  contract/truffle-config.js
  server/controllers/user.controllers.js
  server/models/user.models.js
  server/package.json
  server/routes/index.js
  server/truffle/test/.gitkeep
Labels: 백엔드(backend), 기능 추가(new feature)

#58 [클라이언트] dev 병합
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/base/BaseLayout.js
  client/src/index.js
Labels: 개선안(enhancement), 프론트엔드(frontend)

#59 axios 작업 업데이트
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/base/BaseLayout.js
  client/src/index.js
  contract/abi/shepherdabi.js
  contract/build/contracts/Address.json
  contract/build/contracts/Context.json
  contract/build/contracts/ERC1155.json
  contract/build/contracts/ERC165.json
  contract/build/contracts/IERC1155.json
  contract/build/contracts/IERC1155MetadataURI.json
  contract/build/contracts/IERC1155Receiver.json
  contract/build/contracts/IERC165.json
  contract/build/contracts/Ownable.json
  contract/build/contracts/Shepherd.json
  contract/contracts/.gitkeep
  contract/contracts/Shepherd.sol
  contract/migrations/.gitkeep
  contract/migrations/1_deploy_contracts.js
  contract/package.json
  contract/test/.gitkeep
  contract/truffle-config.js
  server/controllers/user.controllers.js
  server/models/user.models.js
  server/package.json
  server/routes/index.js
  server/truffle/test/.gitkeep
Labels: 개선안(enhancement), 프론트엔드(frontend), 백엔드(backend)

#64 [프론트엔드] useContext 추가
  client/src/App.js
  client/src/Contexts.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/Login.js
  client/src/components/Logo.js
  client/src/features/schema.js
Labels: 개선안(enhancement), 프론트엔드(frontend), 기능 추가(new feature)

#65 통합 병합
  client/src/App.js
  client/src/Contexts.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/Login.js
  client/src/components/Logo.js
  client/src/features/schema.js
  contract/build/contracts/Address.json
  contract/build/contracts/Context.json
  contract/build/contracts/ERC1155.json
  contract/build/contracts/ERC165.json
  contract/build/contracts/IERC1155.json
  contract/build/contracts/IERC1155MetadataURI.json
  contract/build/contracts/IERC1155Receiver.json
  contract/build/contracts/IERC165.json
  contract/build/contracts/Ownable.json
  contract/build/contracts/Shepherd.json
  server/.DS_Store
  server/controllers/main.controllers.js
  server/controllers/tx.controllers.js
  server/controllers/user.controllers.js
  server/middleware/check-auth.js
  server/models/order.models.js
  server/models/user.models.js
  server/routes/index.js
  server/routes/main.route.js
  server/routes/tx.route.js
  server/routes/user.route.js
Labels: 프론트엔드(frontend), 백엔드(backend)

#66 데브 브랜치 반영
  client/src/App.js
  client/src/Contexts.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/Login.js
  client/src/components/Logo.js
  client/src/features/schema.js
  contract/build/contracts/Address.json
  contract/build/contracts/Context.json
  contract/build/contracts/ERC1155.json
  contract/build/contracts/ERC165.json
  contract/build/contracts/IERC1155.json
  contract/build/contracts/IERC1155MetadataURI.json
  contract/build/contracts/IERC1155Receiver.json
  contract/build/contracts/IERC165.json
  contract/build/contracts/Ownable.json
  contract/build/contracts/Shepherd.json
  server/.DS_Store
  server/controllers/main.controllers.js
  server/controllers/tx.controllers.js
  server/controllers/user.controllers.js
  server/middleware/check-auth.js
  server/models/order.models.js
  server/models/user.models.js
  server/routes/index.js
  server/routes/main.route.js
  server/routes/tx.route.js
  server/routes/user.route.js
Labels: 프론트엔드(frontend), 백엔드(backend)

#68 [백엔드][클라이언트] 로그인 구현[WIP]
  .gitignore
  client/.env
  client/package.json
  client/src/App.js
  client/src/components/Header.js
  client/src/components/Login.js
  client/src/components/Logo.js
  client/src/components/PrivateRoute.js
  client/src/components/menu/NavigationMenu.js
  client/src/components/menu/UserMenu.js
  client/src/features/schema.js
  server/app.js
  server/controllers/main.controllers.js
  server/controllers/map.controllers.js
  server/controllers/user.controllers.js
  server/middleware/check-auth.js
  server/models/user.models.js
  server/routes/index.js
  server/routes/ledger.route.js
  server/routes/map.route.js
Labels: 버그(bug), 개선안(enhancement), 프론트엔드(frontend), 백엔드(backend), 기능 추가(new feature)

#71 [클라이언트] 로그인 상황에 따른 라우팅
  client/src/components/Header.js
  client/src/components/LoginForm.js
  client/src/components/Logo.js
  client/src/components/PrivateRoute.js
  client/src/components/menu/NavigationMenu.js
  client/src/components/menu/UserMenu.js
  client/src/index.js
  client/src/pages/Dashboard.js
  client/src/pages/Login.js
  client/src/pages/Main.js
  server/package.json
Labels: 개선안(enhancement), 프론트엔드(frontend), 백엔드(backend)

#72 서버 병합
  server/app.js
  server/controllers/main.controllers.js
  server/controllers/tx.controllers.js
  server/controllers/user.controllers.js
  server/middleware/check-auth.js
  server/models/user.models.js
  server/routes/index.js
  server/routes/main.route.js
  server/routes/tx.route.js
  server/routes/user.route.js
Labels: 버그(bug), 개선안(enhancement), 백엔드(backend), 기능 추가(new feature)

#73 데브 병합 : dev-back-new 내용 반영
  server/controllers/main.controllers.js
  server/controllers/tx.controllers.js
  server/controllers/user.controllers.js
  server/middleware/check-auth.js
  server/models/user.models.js
  server/routes/index.js
  server/routes/main.route.js
  server/routes/tx.route.js
  server/routes/user.route.js
Labels: 버그(bug), 개선안(enhancement), 백엔드(backend), 기능 추가(new feature)

#75 서버 병합 : feat: sendX, sendZ transaction
  .gitignore
  contract/abi/shepherdabi.js
  contract/build/contracts/Address.json
  contract/build/contracts/Context.json
  contract/build/contracts/ERC1155.json
  contract/build/contracts/ERC165.json
  contract/build/contracts/IERC1155.json
  contract/build/contracts/IERC1155MetadataURI.json
  contract/build/contracts/IERC1155Receiver.json
  contract/build/contracts/IERC165.json
  contract/build/contracts/Ownable.json
  contract/build/contracts/Shepherd.json
  contract/migrations/1_deploy_contracts.js
  server/controllers/tx.controllers.js
  server/routes/index.js
  server/routes/tx.route.js
Labels: 버그(bug), 백엔드(backend), 기능 추가(new feature)

#79 [백엔드] tx controller fix
  server/controllers/main.controllers.js
  server/controllers/tx.controllers.js
  server/routes/main.route.js
  server/routes/user.route.js
Labels: 버그(bug), 백엔드(backend)

#80 Dev 병합 - tx controller
  server/controllers/main.controllers.js
  server/controllers/tx.controllers.js
  server/routes/main.route.js
  server/routes/user.route.js
Labels: 버그(bug), 백엔드(backend)
